name: RuboCop Auto Fix

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop auto-correct
        run: bundle exec rubocop -A

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "style: auto-fix RuboCop offenses"
          title: "Auto-fix RuboCop offenses"
          body: |
            This PR contains automatic RuboCop fixes.
          branch: rubocop-auto-fixes
          delete-branch: true
